# Be sure to restart your server when you modify this file.

# Add new mime types for use in respond_to blocks:
# Mime::Type.register "text/richtext", :rtf
# Mime::Type.register_alias "text/html", :iphone
defaults: &defaults
  aeskey: "r0jJjvvm2DzCIf59lsL3JBQDXSFAtahSfEQ9fpdvaOt="
  token: "dYAeWYc"
  corp_id: ""
production:
  <<: *defaults
development:
  <<: *defaults
